spring:
  application:
    name: authentication

  datasource:
    url: jdbc:postgresql://${DB_HOST}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  kafka:
    bootstrap-servers: localhost:29092
    producer:
      group-id: group_id
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

  liquibase:
    change-log: classpath:/db/changelog/users-databaseChangeLog.yaml

  main:
    allow-bean-definition-overriding: true

  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}

  profiles:
    active: prod

logging:
  level:
    org.springframework.security: DEBUG

jwt:
  expiration: ${JWT_EXPIRATION:7000001}
  secretKey: ${JWT_SECRET}

kafka:
  topic:
    email:
      service: user-deactivation

server:
  port: 8082
