version: 2
updates:
  - package-ecosystem: "maven"
    directory: "authentication-service"
    schedule:
      interval: "weekly"
  - package-ecosystem: "maven"
    directory: "gateway-service"
    schedule:
      interval: "weekly"
  - package-ecosystem: "maven"
    directory: "task-service"
    schedule:
      interval: "weekly"
  - package-ecosystem: "maven"
    directory: "mail-sender"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "frontend"
    schedule:
      interval: "weekly"
