version: '3.8'

services:

  test-db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: integration-tests-db
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: sa
    volumes:
      - pg-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - my-network

  consul:
    image: consul:1.10.4
    ports:
      - "8500:8500"

  kibana:
    image: docker.elastic.co/kibana/kibana:8.14.0
    ports:
      - "5601:5601"
    depends_on:
      elasticsearch:
        condition: service_healthy
    networks:
      - my-network

volumes:
  db-data:
  pg-data:


