spring:
  cloud:
    gateway:
      routes:
        - id: auth-service-route
          uri: lb://auth-service
          predicates:
            - Path=/auth/**

        - id: task-service-route
          uri: lb://task-service
          predicates:
            - Path=/api/tasks/**
          filters:
            - name: AuthCheck
              args:
                token: '{token}'
              order: 1
