server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: authentication-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/auth/**
        - id: task-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/tasks/**