server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: task-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/tasks/

        - id: authentication-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/auth/