spring:
  application:
    name: task-service

  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        hostname: localhost
        health-check-path: /actuator/health
        health-check-interval: 10s
        health-check-critical-timeout: 30s
        prefer-ip-address: true
        instance-id: "${spring.application.name}-${server.port}"

  datasource:
    url: jdbc:postgresql://${DB_HOST}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/tasks-databaseChangeLog.yaml

jwt:
  secretKey: ${JWT_SECRET:s3cr3tK3y!@#123ABCdef$%^&*()_+|}{":?><,./;'[]\=-`~}

server:
  port: 8083
